-- CREATE WAREHOUSE SYNTHESIA_WH WITH
-- WAREHOUSE_SIZE = 'X-SMALL'
-- AUTO_SUSPEND = 60
-- AUTO_RESUME = TRUE;

-- CREATE DATABASE SYNTHESIA_DB;

-- CREATE SCHEMA SYNTHESIA_DB.RAW;
-- CREATE SCHEMA SYNTHESIA_DB.STAGING;
-- CREATE SCHEMA SYNTHESIA_DB.ANALYTICS;

-- USE WAREHOUSE SYNTHESIA_WH;
-- USE DATABASE SYNTHESIA_DB;
-- USE SCHEMA RAW;

-- ALTER TABLE SYNTHESIA_DB.RAW."CUSTOMER_CHURN.CSV" RENAME TO SYNTHESIA_DB.RAW.CUSTOMER_CHURN_RAW;

-- DESCRIBE TABLE SYNTHESIA_DB.RAW.CUSTOMER_CHURN_RAW;

-- SELECT *
-- FROM SYNTHESIA_DB.RAW.CUSTOMER_CHURN_RAW
-- where churn != 0
-- LIMIT 10;

-- SELECT * FROM SYNTHESIA_DB.RAW.CUSTOMER_CHURN_RAW
-- SELECT * FROM SYNTHESIA_DB.ANALYTICS.MART_CUSTOMER_CHURN LIMIT 10;