version: 2

models:
  - name: stg_customer_churn
    description: Staging model for raw customer churn data, with cleaned columns.
    columns:
      - name: customer_id
        description: Unique identifier for the customer.
        tests:
          - unique
          - not_null
      - name: age
        description: Age of the customer.
        tests:
          - not_null
          - dbt_utils.at_least_one:
              column_name: age
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 18
              max_value: 100
      - name: gender
        description: Gender of the customer.
        tests:
          - not_null
          - accepted_values:
              values: ['Male', 'Female']

  - name: mart_customer_churn
    description: Final analytics mart model for customer churn analysis.
    columns:
      - name: customer_id
        description: Unique identifier for the customer (from staging).
        tests:
          - unique
          - not_null
      - name: customer_tenure_segment
        description: Categorized segment of customer tenure (New, Mid-Term, Long-Term).
        tests:
          - not_null
          - accepted_values:
              values: ['New Customer (0-11 months)', 'Mid-Term Customer (1-3 years)', 'Long-Term Customer (3+ years)']
      - name: has_churned_flag
        description: Boolean flag indicating if the customer has churned (TRUE/FALSE)
        tests:
          - not_null
          - accepted_values:
              values: [TRUE, FALSE]
      - name: is_total_spend_missing_or_zero
        description: Flag indicating if total spend is null or zero, potentially for new customers
        tests:
          - not_null